version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:CJ@hiranya91@db.fowikjzssfwpzzkvgyel.supabase.co:5432/postgres
    command: npm run dev

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:CJ@hiranya91@db.fowikjzssfwpzzkvgyel.supabase.co:5432/postgres
    restart: unless-stopped